### ISSUE TITLE
New base image with GUS objects and GUS+ApiDB schemas loaded into postgres.

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/vdi-docker-plugin-base#1]
We need a new docker image from which gus dependent plugins will be based.

This image will contain:
* a Postgres instance pre-loaded with:
    * a template database that includes the GUS and ApiDB schemas
    * any necessary preload data (ontologies, etc..)
* the built GUS perl objects

The build will be triggered by:
* Changes to the image dockerfile (such as updating repo commit hashes)
* Changes to the apidb schema repo
* Changes to the gus schema repo

On build this image will need to:
* install postgres as a service
* pull in the veupathdb projects necessary to build the gus objects and db schemas
* pull in the shared perl library used by the apidb and vdi schema installer perl scripts from git
* pull in the gus schema XML files from git
* pull in the apidb schema files from git
* fire up postgres
* load the postgres instance with a new template database
* call the java tool that installs the gus schema into the postgres database
* call the perl script that installs the apidb schema into the postgres database
* write the necessary metadata into the postgres database
* build the gus objects
* shut down the postgres database

At runtime the consuming plugin will:
* Copy the template database into a new temp database
* perform it's plugin-specific processing against the temp database
* produce artifacts
* tear down the temp postgres database
* return artifacts

Additional notes:
* We will need a dev env flag that, when set, causes the plugin to retain the temp databases after process completion

**Comment by Foxcapades** [comment]
What we/I need:
* A listing of the projects necessary to execute the GUS schema installer
* A listing of the projects necessary to execute the ApiDB schema installer
* Research how to trigger the automatic updates to the docker image repo on change to the 2 dependency repos
* Documentation or an explanation of how to build the gus objects

**Comment by steve-fischer-200** [comment]
to answer questions above:
* you just need to add the GusSchema, ApidbSchema and lib-schema-install-utils repos (the latter two are new)
* this document provides instructions how to build the schemas and the obejcts: https://docs.google.com/document/d/1w8DJPMoNh31cTSStuDjlNoZDFj3A4SfX6z0eNH0TsNw/edit
